// flow-typed signature: 6a0e44437ffa9b71d8631ce76261b0a9
// flow-typed version: <<STUB>>/react-responsive-modal_v3.0.0/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-responsive-modal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-responsive-modal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-responsive-modal/__tests__/index' {
  declare module.exports: any;
}

declare module 'react-responsive-modal/__tests__/modal' {
  declare module.exports: any;
}

declare module 'react-responsive-modal/__tests__/setupTests' {
  declare module.exports: any;
}

declare module 'react-responsive-modal/coverage/lcov-report/block-navigation' {
  declare module.exports: any;
}

declare module 'react-responsive-modal/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'react-responsive-modal/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'react-responsive-modal/docs/gatsby-config' {
  declare module.exports: any;
}

declare module 'react-responsive-modal/docs/gatsby-node' {
  declare module.exports: any;
}

declare module 'react-responsive-modal/docs/public/app-1e35e48089d121a8779a' {
  declare module.exports: any;
}

declare module 'react-responsive-modal/docs/public/app-7e291da2625b85d6efba' {
  declare module.exports: any;
}

declare module 'react-responsive-modal/docs/public/app-a278b3d5a28c7e0c3237' {
  declare module.exports: any;
}

declare module 'react-responsive-modal/docs/public/commons-0c9a25ff5fbea943455f' {
  declare module.exports: any;
}

declare module 'react-responsive-modal/docs/public/commons-5b2d6d0a8799bfb4337d' {
  declare module.exports: any;
}

declare module 'react-responsive-modal/docs/public/commons-8151e2c8ba789a994a49' {
  declare module.exports: any;
}

declare module 'react-responsive-modal/docs/public/component---src-pages-index-js-599a2d10a2bf9795beeb' {
  declare module.exports: any;
}

declare module 'react-responsive-modal/docs/public/component---src-pages-index-js-87058b20f16e0c0dee62' {
  declare module.exports: any;
}

declare module 'react-responsive-modal/docs/public/page-component---src-pages-index-js-0d242f49ae3db7a3d35e' {
  declare module.exports: any;
}

declare module 'react-responsive-modal/docs/public/page-component---src-pages-index-js-52725492f58edb914574' {
  declare module.exports: any;
}

declare module 'react-responsive-modal/docs/public/path---index-3164e8ec5c23dfcf778a' {
  declare module.exports: any;
}

declare module 'react-responsive-modal/docs/public/path---index-586c7e095e534a3909ec' {
  declare module.exports: any;
}

declare module 'react-responsive-modal/docs/public/path---index-83b4da74e06ec69fe9e6' {
  declare module.exports: any;
}

declare module 'react-responsive-modal/docs/src/html' {
  declare module.exports: any;
}

declare module 'react-responsive-modal/docs/src/pages/index' {
  declare module.exports: any;
}

declare module 'react-responsive-modal/lib/index.es' {
  declare module.exports: any;
}

declare module 'react-responsive-modal/lib/index' {
  declare module.exports: any;
}

declare module 'react-responsive-modal/rollup.config' {
  declare module.exports: any;
}

declare module 'react-responsive-modal/scripts/generateReactPropsTable' {
  declare module.exports: any;
}

declare module 'react-responsive-modal/src/close-icon' {
  declare module.exports: any;
}

declare module 'react-responsive-modal/src/index' {
  declare module.exports: any;
}

declare module 'react-responsive-modal/src/modal' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-responsive-modal/__tests__/index.js' {
  declare module.exports: $Exports<'react-responsive-modal/__tests__/index'>;
}
declare module 'react-responsive-modal/__tests__/modal.js' {
  declare module.exports: $Exports<'react-responsive-modal/__tests__/modal'>;
}
declare module 'react-responsive-modal/__tests__/setupTests.js' {
  declare module.exports: $Exports<'react-responsive-modal/__tests__/setupTests'>;
}
declare module 'react-responsive-modal/coverage/lcov-report/block-navigation.js' {
  declare module.exports: $Exports<'react-responsive-modal/coverage/lcov-report/block-navigation'>;
}
declare module 'react-responsive-modal/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'react-responsive-modal/coverage/lcov-report/prettify'>;
}
declare module 'react-responsive-modal/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'react-responsive-modal/coverage/lcov-report/sorter'>;
}
declare module 'react-responsive-modal/docs/gatsby-config.js' {
  declare module.exports: $Exports<'react-responsive-modal/docs/gatsby-config'>;
}
declare module 'react-responsive-modal/docs/gatsby-node.js' {
  declare module.exports: $Exports<'react-responsive-modal/docs/gatsby-node'>;
}
declare module 'react-responsive-modal/docs/public/app-1e35e48089d121a8779a.js' {
  declare module.exports: $Exports<'react-responsive-modal/docs/public/app-1e35e48089d121a8779a'>;
}
declare module 'react-responsive-modal/docs/public/app-7e291da2625b85d6efba.js' {
  declare module.exports: $Exports<'react-responsive-modal/docs/public/app-7e291da2625b85d6efba'>;
}
declare module 'react-responsive-modal/docs/public/app-a278b3d5a28c7e0c3237.js' {
  declare module.exports: $Exports<'react-responsive-modal/docs/public/app-a278b3d5a28c7e0c3237'>;
}
declare module 'react-responsive-modal/docs/public/commons-0c9a25ff5fbea943455f.js' {
  declare module.exports: $Exports<'react-responsive-modal/docs/public/commons-0c9a25ff5fbea943455f'>;
}
declare module 'react-responsive-modal/docs/public/commons-5b2d6d0a8799bfb4337d.js' {
  declare module.exports: $Exports<'react-responsive-modal/docs/public/commons-5b2d6d0a8799bfb4337d'>;
}
declare module 'react-responsive-modal/docs/public/commons-8151e2c8ba789a994a49.js' {
  declare module.exports: $Exports<'react-responsive-modal/docs/public/commons-8151e2c8ba789a994a49'>;
}
declare module 'react-responsive-modal/docs/public/component---src-pages-index-js-599a2d10a2bf9795beeb.js' {
  declare module.exports: $Exports<'react-responsive-modal/docs/public/component---src-pages-index-js-599a2d10a2bf9795beeb'>;
}
declare module 'react-responsive-modal/docs/public/component---src-pages-index-js-87058b20f16e0c0dee62.js' {
  declare module.exports: $Exports<'react-responsive-modal/docs/public/component---src-pages-index-js-87058b20f16e0c0dee62'>;
}
declare module 'react-responsive-modal/docs/public/page-component---src-pages-index-js-0d242f49ae3db7a3d35e.js' {
  declare module.exports: $Exports<'react-responsive-modal/docs/public/page-component---src-pages-index-js-0d242f49ae3db7a3d35e'>;
}
declare module 'react-responsive-modal/docs/public/page-component---src-pages-index-js-52725492f58edb914574.js' {
  declare module.exports: $Exports<'react-responsive-modal/docs/public/page-component---src-pages-index-js-52725492f58edb914574'>;
}
declare module 'react-responsive-modal/docs/public/path---index-3164e8ec5c23dfcf778a.js' {
  declare module.exports: $Exports<'react-responsive-modal/docs/public/path---index-3164e8ec5c23dfcf778a'>;
}
declare module 'react-responsive-modal/docs/public/path---index-586c7e095e534a3909ec.js' {
  declare module.exports: $Exports<'react-responsive-modal/docs/public/path---index-586c7e095e534a3909ec'>;
}
declare module 'react-responsive-modal/docs/public/path---index-83b4da74e06ec69fe9e6.js' {
  declare module.exports: $Exports<'react-responsive-modal/docs/public/path---index-83b4da74e06ec69fe9e6'>;
}
declare module 'react-responsive-modal/docs/src/html.js' {
  declare module.exports: $Exports<'react-responsive-modal/docs/src/html'>;
}
declare module 'react-responsive-modal/docs/src/pages/index.js' {
  declare module.exports: $Exports<'react-responsive-modal/docs/src/pages/index'>;
}
declare module 'react-responsive-modal/lib/index.es.js' {
  declare module.exports: $Exports<'react-responsive-modal/lib/index.es'>;
}
declare module 'react-responsive-modal/lib/index.js' {
  declare module.exports: $Exports<'react-responsive-modal/lib/index'>;
}
declare module 'react-responsive-modal/rollup.config.js' {
  declare module.exports: $Exports<'react-responsive-modal/rollup.config'>;
}
declare module 'react-responsive-modal/scripts/generateReactPropsTable.js' {
  declare module.exports: $Exports<'react-responsive-modal/scripts/generateReactPropsTable'>;
}
declare module 'react-responsive-modal/src/close-icon.js' {
  declare module.exports: $Exports<'react-responsive-modal/src/close-icon'>;
}
declare module 'react-responsive-modal/src/index.js' {
  declare module.exports: $Exports<'react-responsive-modal/src/index'>;
}
declare module 'react-responsive-modal/src/modal.js' {
  declare module.exports: $Exports<'react-responsive-modal/src/modal'>;
}
