// flow-typed signature: 6ff9b24f4bbee6e05ddab9ed6286e77e
// flow-typed version: <<STUB>>/react-grid-layout_v0.16.4/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-grid-layout'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-grid-layout' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-grid-layout/build/components/WidthProvider' {
  declare module.exports: any;
}

declare module 'react-grid-layout/build/GridItem' {
  declare module.exports: any;
}

declare module 'react-grid-layout/build/ReactGridLayout' {
  declare module.exports: any;
}

declare module 'react-grid-layout/build/ResponsiveReactGridLayout' {
  declare module.exports: any;
}

declare module 'react-grid-layout/build/responsiveUtils' {
  declare module.exports: any;
}

declare module 'react-grid-layout/build/utils' {
  declare module.exports: any;
}

declare module 'react-grid-layout/interfaces/classnames' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-grid-layout/build/components/WidthProvider.js' {
  declare module.exports: $Exports<'react-grid-layout/build/components/WidthProvider'>;
}
declare module 'react-grid-layout/build/GridItem.js' {
  declare module.exports: $Exports<'react-grid-layout/build/GridItem'>;
}
declare module 'react-grid-layout/build/ReactGridLayout.js' {
  declare module.exports: $Exports<'react-grid-layout/build/ReactGridLayout'>;
}
declare module 'react-grid-layout/build/ResponsiveReactGridLayout.js' {
  declare module.exports: $Exports<'react-grid-layout/build/ResponsiveReactGridLayout'>;
}
declare module 'react-grid-layout/build/responsiveUtils.js' {
  declare module.exports: $Exports<'react-grid-layout/build/responsiveUtils'>;
}
declare module 'react-grid-layout/build/utils.js' {
  declare module.exports: $Exports<'react-grid-layout/build/utils'>;
}
declare module 'react-grid-layout/index' {
  declare module.exports: $Exports<'react-grid-layout'>;
}
declare module 'react-grid-layout/index.js' {
  declare module.exports: $Exports<'react-grid-layout'>;
}
declare module 'react-grid-layout/interfaces/classnames.js' {
  declare module.exports: $Exports<'react-grid-layout/interfaces/classnames'>;
}
