version: '2'
services:
    homehub:
        build: .
        container_name: "homehub1"
        environment:
            - NODE_ENV=development
            - FOO=bar
        ports:
            - 8080:8080
        links:
            - mongodb
        depends_on:
            - mongodb
    mongodb:
        image: mongo:latest
        container_name: "mongodb1"
        ports:
            - 27017:27017
        command: mongod
